### ISSUE TITLE
Zombie Views

### ISSUE THREAD

**Issue by junmich** [kubetz/modular-backbone#3]
Hi,

I crated a modular backbone application with events in view. My problem was, I can't release the views properly so the events fires multiple times. Can anyone help me in this problem?

**Comment by kubetz** [comment]
Sorry for late response.

I hope [this article](https://lostechies.com/derickbailey/2011/09/15/zombies-run-managing-page-transitions-in-backbone-apps/) by Derick Bailey can help.
